ntsstock/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
   #url(r'^account/logout/'),
    url(r'^$', 'stockmanage.views.index', name='index')
    ,url(r'^accounts/login.+','django.contrib.auth.views.login',{'template_name':'stockmanage/login.html'},)   
    ,url(r'^accounts/logout.+','django.contrib.auth.views.logout',{'template_name':'stockmanage/login.html'}, )
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$',include('stockmanage.urls',namespace='stockmanage')),
    ,url(r'^stockmanage/',include('stockmanage.urls',namespace='stockmanage'))
    ,url(r'^admin/', include(admin.site.urls))
)

stockmanage/accounts/urls.py
from django.conf.urls import patterns,url
from stockmanage import views,views_productstock,views_checkbill

urlpatterns=patterns(''
                     ,url(r'^stocklocation/',views.location_index,name='stocklocation_index' )
                     ,url(r'^location_add_modify/',views.location_add_modify,name='location_add_modify' )
                     ,url(r'^location_get/(?P<location_id>\d+)$',views.location_get,name='location_get' )
                     ,url(r'^location_delete/(?P<location_id>\d+)$',views.location_delete,name='location_delete' )
                     #入库单
                     ,url(r'^stockbill/stockin/list/',views.stockbill_stockin_list,name='stockbill_stockin_list' )
                     #出库单
                     ,url(r'^stockbill/stockout/list/',views.stockbill_stockout_list,name='stockbill_stockout_list' )
                      #新建入库
                     ,url(r'^stockbill/stockin/create',views.stockbill_stockin_create,name='stockbill_stockin_create' )
                     #新建出库
                     ,url(r'^stockbill/stockout/create',views.stockbill_stockout_create,name='stockbill_stockout_create' )
                     #编辑入库单
                     ,url(r'^stockbill/stockin/edit/(?P<bill_id>[^/]+)/',views.stockbill_stockin_edit,name='stockbill_stockin_edit' )
                     #编辑出库单
                     ,url(r'^stockbill/stockout/edit/(?P<bill_id>[^/]+)/',views.stockbill_stockout_edit,name='stockbill_stockout_edit' )
                     #编辑单据详情
                     ,url(r'^stockbill/update_detail/(?P<bill_id>[^/]+)/',views.stockbill_update_detail,name='stockbill_update_detail' )
                     #库存清单
                     ,url(r'^productstock/list',views_productstock.list,name='productstock_list' )
                     
                     #######盘点##############
                     #盘点计划列表
                     ,url(r'^checkbill/list',views_checkbill.list,name='checkbill_list')
                     #创建盘点单
                     ,url(r'^checkbill/create',views_checkbill.create,name='checkbill_create')
                     #编辑盘点清单(增加,删除盘点目标)
                     ,url(r'^checkbill/edit/(?P<bill_id>[^/]+)/',views_checkbill.edit,name='checkbill_edit')
                     
                     ,url(r'^$',views.index,name='index')
                     )

stockmanage/urls.py
from django.conf.urls import patterns,url
from stockmanage import views,views_productstock,views_checkbill,views_product,views_init
from stockmanage.views_about import about
from django.views.generic import  TemplateView
from stockmanage.views_checkbill import CheckBillList
from stockmanage.views_bill import BillListView,BillDetailView
from stockmanage.views_productstock import ProductStockList,StockTraceList
from stockmanage.views_init import ViewInitImport
urlpatterns=patterns(''
                     ,url(r'^about/',TemplateView.as_view(template_name='stockmanage/about.html'))
                     ,url(r'^stocklocation/',views.location_index,name='stocklocation_index' )
                     ,url(r'^location_add_modify/',views.location_add_modify,name='location_add_modify' )
                     ,url(r'^location_get/(?P<location_id>\d+)$',views.location_get,name='location_get' )
                     ,url(r'^location_delete/(?P<location_id>\d+)$',views.location_delete,name='location_delete' )
                     #单据列表
                     ,url(r'^bill/list[/]$',BillListView.as_view(template_name='stockmanage/billbase_list.html'),name='bill_list' )
                     ,url(r'^bill/list/(?P<billtype>[^/]+)/',BillListView.as_view(template_name='stockmanage/billbase_list.html'),name='bill_list' )
                     ,url(r'^bill/detail/(?P<pk>[^/]+)/',BillDetailView.as_view(template_name='stockmanage/billbase_detail.html'),name='bill_detail' )

                     #入库单
                     ,url(r'^stockbill/stockin/list/',views.stockbill_stockin_list,name='stockbill_stockin_list' )
                     #出库单
                     ,url(r'^stockbill/stockout/list/',views.stockbill_stockout_list,name='stockbill_stockout_list' )
                     #新建入库
                     ,url(r'^stockbill/stockin/create',views.stockbill_stockin_create,name='stockbill_stockin_create' )
                     #新建出库
                     ,url(r'^stockbill/stockout/create',views.stockbill_stockout_create,name='stockbill_stockout_create' )
                     #编辑入库单
                     ,url(r'^stockbill/stockin/edit/(?P<bill_id>[^/]+)/',views.stockbill_stockin_edit,name='stockbill_stockin_edit' )
                     #编辑出库单
                     ,url(r'^stockbill/stockout/edit/(?P<bill_id>[^/]+)/',views.stockbill_stockout_edit,name='stockbill_stockout_edit' )
                     #编辑单据详情
                     ,url(r'^stockbill/update_detail/(?P<bill_id>[^/]+)/',views.stockbill_update_detail,name='stockbill_update_detail' )
                     #库存清单
                     ,url(r'^productstock/list/',ProductStockList.as_view(paginate_by=20),name='productstock_list' )
                     ,url(r'^productstock/stock_trace/(?P<product_id>[^/]+)/',StockTraceList.as_view(template_name='stockmanage/stocktrace_list.html'),name='productstock_stocktrace_list')
                     #######盘点##############
                     #盘点计划列表
                     ,url(r'^checkbill/list/',CheckBillList.as_view(),name='checkbill_list')
                     ,url(r'^checkbill/create/',views_checkbill.edit,name='checkbill_create')
                     #,url(r'^checkbill/list',views_checkbill.list,name='checkbill_list')
                     #创建盘点单
                     ,url(r'^checkbill/edit/(?P<bill_id>[^/]+)/',views_checkbill.edit,name='checkbill_edit')
                     #编辑盘点清单(增加,删除盘点目标)
                     ,url(r'^checkbill/input_realquantity/(?P<bill_id>[^/]+)/',views_checkbill.input_realquantity,name='checkbill_input_realquantity')
                     #产品详情
                     ,url(r'^product/detail/(?P<product_id>[^/]+)/',views_product.detail,name='product_detail')
                     ,url(r'^init_importdata/',views_init.importdata,name='init_importdata')
                     ,url(r'^user_manual/',TemplateView.as_view(template_name='stockmanage/user_manual.html'),name='user_manual')
                     ,url(r'^$',views.index,name='index')
                     ,
                     )
                     

stockmanage/forms.py
from django import forms
from django.forms import ModelForm
from stockmanage.models import StockBill


class StockBillForm(ModelForm):
    #BillTime=forms.DateTimeFiled(widget=forms.DateInput(attrs={'class':'timepicker'}),required=True)
    #BillNo=forms.CharField(label='鍏ュ簱鍗曞彿')
    #BillReason=forms.ChoiceField()
    def __init__(self, *args, **kwargs):
        super(StockBillForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        #import pdb; pdb.set_trace()
        self.fields['BillReason'] = forms.CharField(max_length=100, label='原因',
                                                    widget=forms.Select(
                                                        choices=
                                                        StockBill.Reason_Choices[0 if instance.BillType == 'in' else 1][
                                                            1]))
        if instance and instance.BillState != instance.state_draft:
            #pass
            #self.fields.add('BillNo')
            #self.fields['BillNo'].widget.attrs['readonly'] = True
            self.fields['BillReason'].widget.attrs['disabled'] = 'disabled'

            self.fields['Memo'].widget.attrs['readonly'] = True
            self.fields['StaffName'].widget.attrs['readonly'] = True

    class Media:
        js = ('stockbill.js',)
        css = {'all': ('css/stockbill.css',)}

    def clean_BillNo(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.BillState != instance.state_draft:
            return instance.BillNo
        else:
            return self.cleaned_data['BillNo']

    def clean_BillReason(self):
        #import pdb;pdb.set_trace()
        instance = getattr(self, 'instance', None)
        if instance and instance.BillState != instance.state_draft:
            return instance.BillReason
        else:
            return self.cleaned_data['BillReason']

    def clean_Memo(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.BillState != instance.state_draft:
            return instance.Memo
        else:
            return self.cleaned_data['Memo']

    def clean_StaffName(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.BillState != instance.state_draft:
            return instance.StaffName
        else:
            return self.cleaned_data['StaffName']

    class Meta:
        model = StockBill
        fields = ['BillReason', 'Memo', 'StaffName']


class CheckBillGenerateForm(forms.Form):
    #generate_type_choices = (('category', 'category'), ('random', 'random'), ('defined_list', 'defined_list'))
    #generate_type = forms.ChoiceField(choices=generate_type_choices)
    product_list=forms.CharField(widget=forms.Textarea)
class InitImportForm(forms.Form):
    file=forms.FileField()

stockmanage/views.py
import string
from datetime import datetime
from django.forms.models import inlineformset_factory
from django.utils import timezone
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import  reverse
from django.views import generic
from django.core import serializers
from stockmanage.models import Product,StockLocation,StockBill,StockBillDetail
from stockmanage.forms import StockBillForm
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# Create your views here.

def index(request):
    #import pdb;pdb.set_trace()
   
    return render(request,'stockmanage/index.html')
def logout(request):
    logout(request)
    HttpResponseRedirect('/')
##############Location COntrol#########################

def location_index(request):
    
    #import pdb;pdb.set_trace()
    all_top_location=StockLocation.objects.filter(ParentLocation=None)
    return render(request,'stockmanage/stocklocation.html',{'all_top_locations':all_top_location})
    pass

def location_add_modify(request):
    location_id=request.POST.get('id')
    parentId =request.POST.get("parentId") 
    if parentId:
        parent=StockLocation.objects.get(pk=parentId)
    else:
        parent=None
    name = request.POST.get("name")
    code = request.POST.get("code")
    desc = request.POST.get("desc")
    location=StockLocation(Name=name,ParentLocation=parent,LocationCode=code,Description=desc)
    if location_id:
        location.id=int(location_id)
    location.save()
    return HttpResponse(location.id)
    
def location_get(request,location_id):
    location=StockLocation.objects.get(pk=location_id)
    jsonLocation=serializers.serialize('json', [location])

    return HttpResponse(jsonLocation,content_type="application/json")

def location_delete(request,location_id):
    location= StockLocation.objects.get(pk=location_id)
    location.delete()
    return HttpResponse("")

def stockbill_list(request,type):
    stockbill_list=StockBill.objects.filter(BillType=type).order_by('-BillTime')
    
    paginator = Paginator(stockbill_list, 5) # Show 25 contacts per page
    page = request.GET.get('page')
    #paginator._count=100
    try:
        stockbill_list_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        stockbill_list_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        stockbill_list_page = paginator.page(paginator.num_pages)

    return render(request,'stockmanage/stockbill.html',
                  {'stockbill_list':stockbill_list_page,'paginator':paginator,
                   'page':stockbill_list_page,
                   'range':paginator.page_range,
                   'type':type})

def stockbill_stockin_list(request):
    return stockbill_list(request,'in')
    
def stockbill_stockout_list(request):
    return stockbill_list(request,'out')
    
def stockbill_stockout_create(request):
    action='create'
    return stockbill_edit(request,'out',None,action)

def stockbill_stockin_create(request):
    action='create'
    #import pdb; pdb.set_trace()
    return stockbill_edit(request,'in',None,action)

def stockbill_stockin_edit(request,bill_id):
    return stockbill_edit(request,'in',bill_id,'.')

def stockbill_stockout_edit(request,bill_id):
    return stockbill_edit(request,'out',bill_id,'.')

def stockbill_edit(request,type,bill_id,action):
    #import pdb; pdb.set_trace()
    if bill_id:
        bill=StockBill.objects.get(pk=bill_id)
    else:
        bill=StockBill(BillType=type,Creator=request.user)
        #bill.BillNo=bill.BillType.upper()+bill.BillNo
    detaillist_formated_text= bill.generat_detail_to_formatedtext()
    if request.method=="GET":
        billform=StockBillForm(instance=bill)
        bill_no=datetime.now().strftime('%Y%m%d%H%M%S%f')
        #import pdb;pdb.set_trace()
        #detaillist_formated_text= bill.generat_detail_to_formatedtext()
        return render(request,'stockmanage/stockbill_edit.html',
                      {'form':billform,
                     #'inline_detain_formset':detail_inlineformset,
                     'detaillist_formated_text':'\n'.join(detaillist_formated_text),
                     'bill':bill,'action':action,
                     'bill_no':bill_no})
 
    elif request.method=='POST':
        p=request.POST.copy()
        if 'savedraft' in p:
            #import pdb;pdb.set_trace()
            
            stockbill_update_detail(request,bill)
            print('detailcount after return')
            print(bill.billdetailbase_set.count())
            pass
        elif 'apply' in p:
            bill.BillState='applied'
            #bill.apply_stock_change()
            pass
        elif 'pass' in p:
            p["BillReason"]=bill.BillReason
            bill.BillState='checked'
        elif 'refused' in p:
            p["BillReason"]=bill.BillReason
            bill.BillState='draft'
        elif 'tt_billdetail' in p:
           return stockbill_update_detail(request,bill)
        else:
            raise Exception('No Such Action')
        
        
        #form=StockBillForm(request.POST,instance=bill)
        billform=StockBillForm(p,instance=bill)
        #detail_inlineformset=billdetail_formset_factory(request.POST,request.FILES, instance=bill)
        if billform.is_valid():
            billform.save()
            if 'savedraft' in p:
                pass
                import pdb;pdb.set_trace()
                stockbill_update_detail(request,bill)
                #saved_bill.save()
        else:
            return render(request,'stockmanage/stockbill_edit.html',{"form":billform})
            #if detail_inlineformset.is_valid():
                #detail_inlineformset.save()
        if not bill_id:
            return HttpResponseRedirect(reverse('stockmanage:stockbill_stockin_edit',args=[bill.id]))
       
    return render(request,'stockmanage/stockbill_edit.html',
              {'form':billform,
             'detaillist_formated_text':'\n'.join(detaillist_formated_text),
             'bill':bill,'action':action})     
    
def stockbill_update_detail(request,bill):
    
    detaillist=bill.billdetailbase_set.all()
    bill.billdetailbase_set.clear()
    detaillist=[]
    formated_text=request.POST['tt_billdetail']
    for line in formated_text.splitlines():
        if not line:
            continue
        #import pdb;pdb.set_trace()
        procode=line.split(',')[0]
        product=Product.objects.get(Code_Original=procode)
        qty=line.split(',')[1]
        location_code=line.split(',')[2]
        location=StockLocation.objects.get(LocationCode=location_code)
        detail=StockBillDetail(stockbill=bill,product=product,location=location,Quantity=qty)
        print('detail')
        print(detail.quantity)
        #[bill.billdetailbase_set].append(detail) #
        bill.billdetailbase_set.add(detail)
        print('detailcount after parse text')
        print (bill.billdetailbase_set.count())
        #import pdb; pdb.set_trace()
        #detaillist_formated_text=bill.generat_detail_to_formatedtext()
    '''return render(request,'stockmanage/stockbill_edit.html',
                      {'form':StockBillForm(instance=bill),
                     #'inline_detain_formset':detail_inlineformset,
                     'detaillist_formated_text':'\n'.join(detaillist_formated_text),
                     'bill':bill,'action':'.'})
                     '''
def productstock_list(request):
    return HttpResponse('产品库存列表')
    pass

stockmanage/templates/stockmanage/about.html
{% extends "stockmanage/base.html" %}
{%load staticfiles%}
{%block header%}
<link rel="stylesheet" type="text/css"  href="{%static 'stockmanage/css/stockbill.css'%}" media='screen,projector'/>

<script type="text/javascript" src="{%static 'stockmanage/bootstrap-3.1.1-dist/js/bootstrap.min.js'%}"></script>
<script type="text/javascript" src="{%static 'stockmanage/js/bootstrap-confirmation.js'%}"></script>
<script type="text/javascript" src="{%static 'stockmanage/js/stockbill.js'%}"></script>
{%endblock%}
{%block content_title%}
About this Site
{%endblock%}

{%block nav_stockin_create%}
{%if not bill.id and  bill.BillType == 'in'%}
active
{%endif%}
{%endblock%}
{%block nav_stockout_create%}
{%if not bill.id and  bill.BillType == 'out'%}
active
{%endif%}
{%endblock%}
{%block content%}
{{company_name}}bts
{%endblock%}

stockmanage/templates/stockmanage/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="{%static 'stockmanage/jquery/jquery-1.9.1.js'%}" type="text/javascript"></script>
		<script src="{%static 'stockmanage/jquery/jqueryui/jquery-ui-1.10.3.min.js'%}" type="text/javascript"></script>
		<!--jQueryUI-->
		<link rel="stylesheet" type="text/css" media="all" href="{%static 'stockmanage/jquery/jqueryui/themes/base/jquery-ui.css'%}" />
		
		<!--bootstrap-->
		<link rel="stylesheet" type="text/css"  href="{%static 'stockmanage/bootstrap-3.1.1-dist/css/bootstrap.min.css'%}" media='screen,projector'/>
		<link rel="stylesheet" type="text/css"  href="{%static 'stockmanage/bootstrap-3.1.1-dist/css/bootstrap-theme.min.css'%}" media='screen,projector'/>
 
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'stockmanage/js/html5shiv.js'%}"></script>
      <script src="{%static 'stockmanage/js/respond.min.js'%}"></script>
     <![endif]-->

		{%block header%}{%endblock%}
		<title>{%block title%}NTS 展厅管理{%endblock%}</title>

	</head>
	<body>
		<div class="container">
			<div class='row'>
				<h1 class='col-sm-10'>NTS Stock Management</h1>
				<div class='col-sm-2'>
					{%if user%} {{user}}<a href="/accounts/logout/">注销</a>{%endif%}
				</div>
			</div>
			<hr/>
			<!--Left Menu-->
			<div class="row">
				<div id="lm" class='col-sm-2 list-group'>
					<a class='list-group-item {%block nav_stocklist%}{%endblock%}'href="/stockmanage/productstock/list"><span style='margin-right: 15px' class="glyphicon glyphicon-home"> </span>库存列表</a>
					<a  class='list-group-item {%block nav_location%}{%endblock%}'href="/stockmanage/stocklocation/"><span style='margin-right: 15px'  class="glyphicon glyphicon-th"> </span>展位管理</a>
					<a  class='list-group-item {%block nav_stockin_list%}{%endblock%} 'href="/stockmanage/stockbill/stockin/list/"><span  style='margin-right: 15px' class="glyphicon glyphicon-align-left"> </span>入库列表</a>
					<a class='list-group-item {%block nav_stockout_list%}{%endblock%}' href="{%url 'stockmanage:stockbill_stockout_list'%}"><span style='margin-right: 15px'  class="glyphicon glyphicon-align-right"> </span>出库列表</a>
					<a class='list-group-item {%block nav_stockin_create%}{%endblock%}' href="{%url 'stockmanage:stockbill_stockin_create'%}"> <span  style='margin-right: 15px' class="glyphicon glyphicon-import"> </span>新建入库</a>
					<a  class='list-group-item {%block nav_stockout_create%}{%endblock%}' href="{%url 'stockmanage:stockbill_stockout_create'%}"><span style='margin-right: 15px'  class="glyphicon glyphicon-export"> </span>新建出库</a>
					<a class='list-group-item {%block nav_check_list%}{%endblock%}' href="{%url 'stockmanage:checkbill_list'%}"><span  style='margin-right: 15px' class="glyphicon glyphicon-ok"> </span>盘点列表</a>
				    <a class='list-group-item {%block nav_check_create%}{%endblock%}' href="{%url 'stockmanage:checkbill_create'%}"><span  style='margin-right: 15px' class="glyphicon glyphicon-pencil"> </span>创建盘点</a>
 <a class='list-group-item {%block nav_init_import%}{%endblock%}' href="{%url 'stockmanage:init_importdata'%}"><span  style='margin-right: 15px' class="glyphicon glyphicon-pencil"> </span>初始化导入</a>
<a class='list-group-item {%block nav_user_manual%}{%endblock%}' href="{%url 'stockmanage:user_manual'%}"><span  style='margin-right: 15px' class="glyphicon glyphicon-pencil"> </span>使用手册</a>
                </div>
				<!--Main Content-->
				<div id='mc' class='col-sm-10'>
					<h2>{%block content_title%}Stock Manage{%endblock%}</h2>
					{%block content%}my default content{%endblock%}
				</div>

				<hr/>
			</div>
			<footer>
				<span>----------------NTS-----------------</span>
			</footer>
		</div>
		<script src="{%static 'stockmanage/bootstrap-3.1.1-dist/js/bootstrap.js'%}" type="text/javascript"></script>
		<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://a.nts.com/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "2"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
	</body>
</html>

stockmanage/templates/stockmanage/checkbill_edit.html
{% extends "stockmanage/base.html" %}
{%block content_title%}
盘点单详情
{%endblock%}
{%block nav_check%}
active
{%endblock%}				
{%block content%}
<div class="panel panel-default">
	<div class="panel-heading">
		<label>单号</label>:{{bill.BillNo}}<label>创建日期</label>:{{bill.BillTime}}<label>当前状态:</label>{{bill.CheckState}}
	</div>
	<div class="panel-body">
		<form action='.' method="post"> {% csrf_token %} 
			<input type="hidden" name='bill_id' value='{{bill.id}}'>
			<table class="table table-hover">
				<thead>
					<tr>
						<td>产品</td><td>位置</td><td>系统数量</td>
						{%if bill.CheckState == 'progressing' or bill.CheckState == 'complete' %}
						<td>真实数量</td>
						{%endif%}
					</tr>
				</thead>
				<tbody>
					{% for detail in bill.checkbilldetail_set.all %}
					<tr>
						<td>{{ detail.product.NTSCode }}</td>
						<td>{{ detail.location}}</td>
						<td>{{ detail.quantity}}</td>
						{%if bill.CheckState == 'progressing'%}<td>
							<input name='hi_detail_id' type='hidden' value='{{detail.id}}'/>
						<input type="text" name='tbx_realquantity'  class="text-info" value='{{ detail.realquantity }}' />
						</td>{%endif%}
						{%if bill.CheckState == 'complete'%}<td>
						{{detail.realquantity}}
						</td>{%endif%}
					</tr>
					{% endfor %}
				</tbody>
			</table>
			
			{%if bill.CheckState == 'draft' %}
			<button class="btn btn-default" name='begin_check'>
				开始盘点
			</button>
			{%elif bill.CheckState == 'progressing' %}
			<button class="btn btn-default" name='save'>
				暂存
			</button>
			<button class="btn btn-default" name='complete_check'>
				完成输入,结束盘点.
			</button>
			{%else%}
			{%endif%}
			<button class="btn btn-default" name='download_as_excel'>
				下载为Excel
			</button>
		</form>
	</div>
</div>
{%endblock%}

stockmanage/templates/stockmanage/checkbill_list.html
{% extends "stockmanage/base.html" %}
{%block content_title%}
<span class='sub-header'>盘点单列表</span>
{%endblock%}{%block nav_check_list%}
active
{%endblock%}
{%block content%}

<table class="table">
	<thead>
	<tr>
		<th>单号</th><th>时间</th><th>状态</th><th> </th>
	</tr></thead>
	{%for checkbill in object_list%}
	<tr>
		<td>{{checkbill.BillNo}}</td>
		<td>{{checkbill.BillTime}}</td>
		<td>{{checkbill.CheckState}}</td>
		<td><a href="{%url 'stockmanage:checkbill_edit' checkbill.id %}">详情</a></td>
	</tr>
	
	{%endfor%}
</table>
{%include 'stockmanage/widget_paginator.html'%}
<a class="button" href="{%url 'stockmanage:checkbill_create'%}">新建盘点单</a>


{%endblock%}

stockmanage/templates/stockmanage/productstock_list.html
{% extends "stockmanage/base.html" %}
{%load staticfiles%}

{%block header%}

{%endblock%}
{%block content_title%}
当前库存情况
{%endblock%}{%block nav_stocklist%}
active
{%endblock%}
{%block content%}
<form class="navbar-form" role="search">
  <div class="form-group">
    <input type="text" class="form-control" value='{{kw}}' name='kw' placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

{% if productstock_list_page %}

<table class="table">
	<tr>
		<td>货品代码</td><td>货品名称</td><td>位置</td><td>数量</td><td></td>
	</tr>
	{%for stock in productstock_list_page%}
	<tr><td>{{stock.product.Code_Original}}</td>
		<td>{{stock.product}}</td>
		<td>{{stock.stocklocation}}</td>
		<td>{{stock.quantity}} </td>
		<td> <a href="{%url 'stockmanage:productstock_stocktrace_list' stock.product.id%}">历史记录</a>
			 <a href="{%url 'stockmanage:product_detail' stock.product.id%}">货品详情</a> </td>
	</tr>
	{%endfor%}
</table>
{%else%}
<p>
	No data are availabel.
</p>
{%endif%}
{%include 'stockmanage/widget_paginator.html'%}

<div>

</div>
{%endblock%}

stockmanage/templates/stockmanage/stockcheck_edit.html
{% extends "stockmanage/base.html" %}
{%block content_title%}
填写盘点详情.
{%endblock%}
{%block content%}



{%endblock%}